apiVersion: v1
kind: Namespace
metadata:
  name: user-container-selinux
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-container-selinux
  namespace: user-container-selinux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-container-selinux
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-container-selinux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-container-selinux
subjects:
- kind: ServiceAccount
  name: user-container-selinux
  namespace: user-container-selinux
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: container-selinux-policy
  namespace: user-container-selinux
spec:
  selector:
    matchLabels:
      app: container-selinux-policy
  template:
    metadata:
      labels:
        app: container-selinux-policy
    spec:
      initContainers:
      - name: container-selinux-init
        image: >-
          quay.io/ocpeng/intel_policy_deploy:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: var-lib-selinux
          mountPath: /var/lib/selinux
        - name: etc-selinux
          mountPath: /etc/selinux
      containers:
      - name: container-selinux
        image: >-
         registry.access.redhat.com/ubi8-minimal:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 60; done;" ]
      volumes:
      - name: var-lib-selinux
        hostPath:
          path: /var/lib/selinux
          type: DirectoryOrCreate
      - name: etc-selinux
        hostPath:
          path: /etc/selinux
          type: DirectoryOrCreate
      serviceAccountName: user-container-selinux
